# Generated by Django 5.1.4 on 2025-01-02 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='Name',
            new_name='Category_Name',
        ),
    ]
