# Generated by Django 5.1.4 on 2025-01-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_productdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('cat_profile', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
    ]
