# Generated by Django 5.1.4 on 2025-01-17 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_servicedb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedb',
            old_name='cat_profile',
            new_name='ser_profile',
        ),
        migrations.RenameField(
            model_name='servicedb',
            old_name='Category_Name',
            new_name='service_Name',
        ),
    ]
